complex-page-review
kprvlv/yard-frontend pull request #1
Opened 2017-06-15 16:21 UTC by kprvlv

2017-06-15 17:56 UTC, imevro requested changes
https://rawgit.com/kprvlv/yard-frontend/develop/complex.html
кнопка contact the team не тем шрифтом

почему список ЖК находится в complex.html, а не complexes?

2017-06-15 21:29 UTC, imevro requested changes

2017-06-15 21:29 UTC, evgenyrodionov commented on complexes.html
> +        <nav class="navmenu">
.main-header > .compass-logo + .navmenu?  Что с неймингом? Где консистентность?

2017-06-15 21:29 UTC, evgenyrodionov commented on complexes.html
> +          <a class="navmenu-link agents" href="">Наши агенты</a>
зачем эти классы buy rent agents?

2017-06-15 21:29 UTC, evgenyrodionov commented on complexes.html
> +            <h4 class="footer-h4">ООО «Ярд»</h4>
что будет, если мы заменим тег на h5? Не именуй классы по тегам

2017-06-15 21:29 UTC, evgenyrodionov commented on style.css
> +  margin-left: 328px;
Зачем

2017-06-15 21:29 UTC, evgenyrodionov commented on style.css
> +.card-bitmap {
image, что за битмап

2017-06-15 21:29 UTC, evgenyrodionov commented on style.css
> +  padding: 12px 32px 12px 32px;
12px 32px

2017-06-15 21:29 UTC, evgenyrodionov commented on style.css
> +  height: 20px;
сказал не ставить

2017-06-15 21:29 UTC, evgenyrodionov commented on style.css
> +  padding: 24px 100px 0 16px;
что за разнобой

2017-06-15 21:29 UTC, evgenyrodionov commented on style.css
> +  max-width: 698px;
не ставить

2017-06-15 21:29 UTC, evgenyrodionov commented on style.css
> +  height: 22px;
нет

2017-06-15 21:29 UTC, evgenyrodionov commented on style.css
> +.footer-p {
что за p?

2017-06-16 21:13 UTC, evgenyrodionov commented on style.css
> +  height: 20px;
пока ты игноришь мои замечания — я не проверяю дальше

2017-06-16 21:13 UTC, imevro requested changes

2017-06-16 21:13 UTC, evgenyrodionov commented on style.css
> +  height: 20px;
пока ты игноришь мои замечания — я не проверяю дальше

2017-06-17 10:22 UTC, imevro requested changes
https://rawgit.com/kprvlv/yard-frontend/develop/complex.html

картинкам пiзда

2017-06-17 10:22 UTC, evgenyrodionov commented on complex.html
> +          <a class="navmenu-link" href="">Купить</a>
.main-header-navmenu > .navmenu-link? Где согласованность?

2017-06-17 10:22 UTC, evgenyrodionov commented on complex.html
> +        <div>
а зачем тут пустой див

2017-06-17 10:22 UTC, evgenyrodionov commented on complex.html
> +  <div>
и тут

2017-06-17 10:22 UTC, evgenyrodionov commented on complex.html
> +  <div class="gallery">
почему выше у тебя комплекс-хедер, а тут галлери?

2017-06-17 10:22 UTC, evgenyrodionov commented on complex.html
> +      <div class="main">
а тут маин

2017-06-17 10:22 UTC, evgenyrodionov commented on complex.html
> +  <div class="features-border">
Попробуй hr

2017-06-17 10:22 UTC, evgenyrodionov commented on complex.html
> +    <div class="container">
почему не обернешь всю страницу в один контейнер?

2017-06-17 10:22 UTC, evgenyrodionov commented on complex.html
> +            <p class="infrastructure-text">Частная школа</p>
неправильно, частная школа идёт на следующей строке после последнего элемента в строке, а не в первой колонке

2017-06-18 00:32 UTC, evgenyrodionov commented
Коммиты абсолютно хуевые и не отражают суть сделанной работы между ними

2017-06-18 00:33 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27257225-d1eb4e4a-53d6-11e7-9a93-225fbf0c300b.png)

2017-06-18 00:33 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27257229-e579f4b6-53d6-11e7-9c80-b2ce92493b89.png)

2017-06-18 00:34 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27257231-f1eef264-53d6-11e7-9ff0-92ab3212de0c.png)

2017-06-18 00:34 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27257234-fc252b68-53d6-11e7-9d67-4b3994bc931a.png)

2017-06-18 00:36 UTC, imevro requested changes

2017-06-18 00:36 UTC, evgenyrodionov commented on style.css
> +/* complex.html styles*/
вынеси это в комплекс.цсс значит

2017-06-18 00:36 UTC, evgenyrodionov commented on style.css
> +.combined-shape {
классное название

2017-06-18 00:36 UTC, evgenyrodionov commented on style.css
> +  background-color: white;
не пиши везде white, повесь на бади класс

2017-06-18 13:36 UTC, evgenyrodionov commented
а почему тут ras pee dora see low?

![image](https://user-images.githubusercontent.com/775692/27261067-3d27089e-5444-11e7-8e36-e30955f2645d.png)

2017-06-18 13:37 UTC, imevro requested changes
дизайн ↑

2017-06-18 13:37 UTC, evgenyrodionov commented on complex-style.css
> +button {
это что

2017-06-18 18:05 UTC, merged

2017-06-18 18:06 UTC, evgenyrodionov commented
гит фетч --олл, гит чекаут мастер, гит пулл --ребейз