Develop eslint
kprvlv/yard-frontend pull request #3
Opened 2017-06-26 20:13 UTC by kprvlv

2017-06-27 14:28 UTC, evgenyrodionov commented
Жду разрешения конфликтов

2017-06-27 23:15 UTC, imevro requested changes

2017-06-27 23:15 UTC, evgenyrodionov commented on src/App.test.jsx
> +/* eslint-disable */
мы отключаем только специфическое правило в конкретном файле, а не весь еслинт

2017-06-27 23:15 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +  padding-left: 32px;
красава!

2017-06-27 23:15 UTC, evgenyrodionov commented on src/Complexes/List/Description.jsx~HEAD
> +import React, { Component } from "react";
этот файл лишний, он остался после мерджконфликтов

2017-06-27 23:15 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +import React from 'react';
реакт первой строкой импортируем всегда

2017-06-28 18:05 UTC, imevro requested changes

2017-06-28 18:05 UTC, evgenyrodionov commented on package.json
> +    "now": "^7.1.0",
а зачем это в депс

2017-06-29 16:24 UTC, kprvlv commented
https://build-yard-adidohtslt.now.sh/

2017-06-29 16:43 UTC, merged

2017-06-29 16:43 UTC, evgenyrodionov commented
не забудь сделать гит фетч --олл, гит чекаут мастер, гит пулл --ребейз и от мастера новый ПР